site_name: OverrideAudit Documentation
site_author: Terence Martin (OdatNurd)
site_url: https://codebyzach.github.io/sublime_override_audit
repo_url: https://github.com/CodeByZach/sublime_override_audit
edit_uri: tree/master/docs/src/content
copyright: '&copy {{ current_year }} <a href="https://odatnurd.net">OdatNurd</a>'

docs_dir: content
site_dir: site
hooks:
  - extensions/hooks.py

nav:
  - Home:
    - "About OverrideAudit": index.md
  - Installation:
    - "How to Install": install/index.md
  - Configuration:
    - "Package Setup": config/index.md
    - "Key Bindings": config/keybinds.md
    - "Settings": config/settings.md
  - "Terminology":
    - "OverrideAudit Terminology": terminology/index.md
    - "What is an Override": terminology/overrides.md
  - Usage:
    - "QuickStart": usage/index.md
    - "Workflow": usage/workflow.md
    - "Commands": usage/commands.md
  - "Reports":
    - "OverrideAudit Reports": reports/index.md
    - "Package Report": reports/package.md
    - "Override Report": reports/override.md
    - "Bulk Diff Report": reports/bulkdiff.md
  - Changelog:
    - "Changelog": changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CodeByZach
      name: CodeByZach on GitHub
  generator: true

theme:
  name: material
  language: en
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: simple/sublimetext
    repo: fontawesome/brands/github
  favicon: /favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: orange
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: orange
      accent: indigo

extra_css:
  - stylesheets/custom.css

plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
      auto_caption: true
  - macros:
      on_error_fail: true
      on_undefined: strict
      module_name: extensions/macros
  - minify:
      minify_html: true
  - search
  - social:
      cards_dir: images/social
      cards_layout_options:
        font_family: Lilita One

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
  - pymdownx.tilde
  - toc:
      title: On this page
      permalink: ⚓︎
      permalink_title: Link to this section for future reference
